// <auto-generated />
using System.Collections.Generic;
using JobHunt.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHunt.Core.Data.Migrations
{
    [DbContext(typeof(JobHuntDb))]
    partial class JobHuntDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("JobHunt.Core.Applications.ApplicationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ApplicationEvents");
                });

            modelBuilder.Entity("JobHunt.Core.Applications.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AppliedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverLetterHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLetterPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobPostingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutcomeUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("RunLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt");

                    b.HasIndex("JobPostingId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("JobHunt.Core.Hunting.HuntRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobsNew")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobsRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SearchProfileId");

                    b.ToTable("HuntRuns");
                });

            modelBuilder.Entity("JobHunt.Core.Hunting.SearchProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastRunAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDocumentsPerHunt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreThreshold")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("SearchTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Weights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("JobHunt.Core.Jobs.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplicantCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("BoardShowsApplied")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ClearanceRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractDurationText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContractMonths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLetterGeneratedHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLetterPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DetailsReadAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DocumentsGeneratedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("FilterReasons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenAt")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("FoundBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsStaffingAgency")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlainDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PostedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("RedFlags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeGeneratedHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryMax")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryMin")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoreBreakdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SelectedForApply")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SponsorshipAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsQuickApply")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UnderstoodAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "BoardId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("UserProfileId", "Status", "Score");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Accomplishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Accomplishment");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.BoardAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSignIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignInEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "BoardId")
                        .IsUnique();

                    b.ToTable("BoardAccount");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Bullet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkExperienceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkExperienceId");

                    b.ToTable("Bullet");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Certification");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.CustomField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("CustomField");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Coursework")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gpa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Graduated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Honors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Minor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.KeywordList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("KeywordList");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.LanguageSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("LanguageSkill");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.ProfileLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ProfileLink");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearsKnown")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.ScreeningAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedQuestion");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ScreeningAnswer");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Featured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Years")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.TextBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("TextBlock");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Authorization", "JobHunt.Core.Profile.UserProfile.Authorization#WorkAuthorization", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("AuthorizedCountries")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Citizenship")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("ClearanceActive")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("ConsentsToBackgroundCheck")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("ConsentsToDrugTest")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasDriversLicense")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasNonCompete")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("HasReliableTransportation")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsOver18")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("NonCompeteDetails")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("PreviouslyEmployedAtTarget")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("RequiresSponsorship")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("SecurityClearance")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("VisaStatus")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("WorkPermitExpires")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Compensation", "JobHunt.Core.Profile.UserProfile.Compensation#Compensation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("CurrentAnnualSalary")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DesiredAnnualSalary")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("DesiredHourlyRate")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("MinimumAnnualSalary")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MinimumHourlyRate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("OpenToEquity")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "JobHunt.Core.Profile.UserProfile.Contact#ContactInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneCountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneType")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreferredName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Pronouns")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SecondaryEmail")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SecondaryPhone")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Suffix")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Address", "JobHunt.Core.Profile.UserProfile.Contact#ContactInfo.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("County")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Street1")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Street2")
                                        .IsRequired()
                                        .HasColumnType("TEXT");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Disclosures", "JobHunt.Core.Profile.UserProfile.Disclosures#VoluntaryDisclosures", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DisabilityStatus")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RaceEthnicity")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SexualOrientation")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("VeteranStatus")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Preferences", "JobHunt.Core.Profile.UserProfile.Preferences#WorkPreferences", b1 =>
                        {
                            b1.IsRequired();

                            b1.PrimitiveCollection<string>("AvoidIndustries")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("CanBeOnCall")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CanWorkShifts")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("CanWorkWeekends")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("CompanyBlocklist")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("DesiredTitles")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EarliestStartDate")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxCommuteMiles")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxTravelPercent")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("MinimumContractMonths")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("NoticePeriodWeeks")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("PreferredCompanySizes")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("PreferredIndustries")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("PreferredTimeZones")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("RelocationLocations")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("WantsContract")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WantsContractToHire")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WantsFullTime")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WantsHybrid")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WantsOnSite")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WantsPartTime")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WantsRemote")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("WillingToRelocate")
                                .HasColumnType("INTEGER");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Summary", "JobHunt.Core.Profile.UserProfile.Summary#ProfessionalSummary", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Headline")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("HighestEducation")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("TotalYearsExperience")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.WorkExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Employer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FinalAnnualSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MayContact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonForLeaving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasRemote")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("WorkExperience");
                });

            modelBuilder.Entity("JobHunt.Core.Settings.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyApplyCap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DryRun")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxActionDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinActionDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreflightQuestionScan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedLlmProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("JobHunt.Core.Applications.ApplicationEvent", b =>
                {
                    b.HasOne("JobHunt.Core.Applications.JobApplication", null)
                        .WithMany("Events")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunt.Core.Applications.JobApplication", b =>
                {
                    b.HasOne("JobHunt.Core.Jobs.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobHunt.Core.Hunting.SearchProfile", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunt.Core.Jobs.JobPosting", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Accomplishment", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Accomplishments")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.BoardAccount", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("BoardAccounts")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Bullet", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.WorkExperience", null)
                        .WithMany("Bullets")
                        .HasForeignKey("WorkExperienceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Certification", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Certifications")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.CustomField", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("CustomFields")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Education", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Education")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.KeywordList", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("KeywordLists")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.LanguageSkill", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Languages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.ProfileLink", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Links")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Project", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Reference", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("References")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.ScreeningAnswer", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Answers")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.Skill", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Skills")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.TextBlock", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("TextBlocks")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Profile.WorkExperience", b =>
                {
                    b.HasOne("JobHunt.Core.Profile.UserProfile", null)
                        .WithMany("Experience")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobHunt.Core.Applications.JobApplication", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("JobHunt.Core.Jobs.JobPosting", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.UserProfile", b =>
                {
                    b.Navigation("Accomplishments");

                    b.Navigation("Answers");

                    b.Navigation("BoardAccounts");

                    b.Navigation("Certifications");

                    b.Navigation("CustomFields");

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("KeywordLists");

                    b.Navigation("Languages");

                    b.Navigation("Links");

                    b.Navigation("Projects");

                    b.Navigation("References");

                    b.Navigation("Skills");

                    b.Navigation("TextBlocks");
                });

            modelBuilder.Entity("JobHunt.Core.Profile.WorkExperience", b =>
                {
                    b.Navigation("Bullets");
                });
#pragma warning restore 612, 618
        }
    }
}
